# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Social Network' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Social Network
  
  pod 'Kingfisher'

  # Alamofire
  pod 'Alamofire', '~> 4.7'
  pod 'AlamofireNetworkActivityLogger'

  # API
  pod 'SwiftyJSON'
  pod 'ObjectMapper'

  # Reactive
  pod 'RxSwift',    '~> 4.0'
  pod 'RxCocoa',    '~> 4.0'

  # Firebase
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'
  pod 'Firebase/Analytics'
  pod 'Firebase/Storage'

  pod 'IQKeyboardManagerSwift'
  
  pod 'BSImagePicker'
  
  #Side Menu
  pod 'SideMenu'

end
